name=RobotEye
version=1.0.0
author=fonzu <fonzu@users.noreply.github.com>
maintainer=fonzu <fonzu@users.noreply.github.com>
sentence=An  robot eye 
paragraph=This library supports smooth morphing expressions, custom face generator for ESP32 with U8G2.
category=Display
url=https://github.com/fonzu/RobotEye
architectures=esp32
depends=U8g2,Wire
